version: '3'

services:
  # rabbitmq:
  #   image: "rabbitmq:3.7-management-alpine"
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

  postgresql:
    image:  "postgres:10-alpine"
    environment:
      POSTGRES_USER: "newslyzer"
      POSTGRES_PASSWORD: "newslyzer"
      PGDATA: "/var/lib/postgresql/data/pgdata"

    volumes:
      - "./pgdata:/var/lib/postgresql/data/pgdata"

    ports:
      - "5432:5432"

  redis:
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"

  api-server:
    image: newslyzer/api-server
    build:
      context: ../api
      dockerfile: docker/api.docker

    links:
      - redis
      - postgresql

    ports:
      - "80:80"

#  workers:
#    build:
#      image: newslyzer/workers
#      context: ../workers
#      dockerfile: workers.docker
