version: '2.0'

services:
  redis:
    image: "redis:5.0-alpine"
    ports:
      - "6379:6379"

  front-data:
    image: newslyzer/frontend
    build:
      context: ../front
      dockerfile: docker/Dockerfile

    volumes:
      - data:/data

  api-server:
    image: newslyzer/api-server
    build:
      context: ../api
      dockerfile: docker/Dockerfile
    links:
      - redis
    volumes:
      - sockets:/tmp
      - data:/data
    environment:
      - REDIS_HOST=redis
      - WORDCLOUD_PATH=https://warm-catfish-33.localtunnel.me/wordcloud
    command: [ "sh", "-c", "cp /data/index.html /newslyzer/api/templates/ && /start.sh"]

  nginx:
    image: newslyzer/nginx
    build:
      context: ./nginx
    volumes:
      - data:/data
      - wordcloud:/data/wordcloud
      - sockets:/tmp
    ports:
      - "3333:80"
      
  workers:
    image: newslyzer/workers
    build:
      context: ../workers
      dockerfile: docker/Dockerfile
    links:
      - redis
    volumes:
      - wordcloud:/data/wordcloud
    environment:
      - REDIS_HOST=redis
      - WORDCLOUD_PATH=/data/wordcloud
      
  flower:
    image: mher/flower
    links:
      - redis
    command: --broker=redis://redis:6379
    ports:
      - "5555:5555"

volumes:
  sockets:
    driver: local
  wordcloud:
    driver: local
  db-data:
    driver: local
  data:
    driver: local
